#!/usr/bin/env bash

selectWorkspace () { 
  # Using find to search folders containing workspaces
  local myDirs=$(find ~/school/ ~/personal/ ~/work/ -mindepth 1 -maxdepth 1 -type d && \
    echo ~/.dotfiles/; ) # Add additional workspaces here

  local workspace=$(echo "$myDirs" | fzf)
  echo "$workspace"
}

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(selectWorkspace)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

tmux switch-client -t "$selected_name"
