c = c
config = config
# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)

# Position of the tab bar.
# Type: Position
# Valid values:
#   - top
#   - bottom
#   - left
#   - right
c.tabs.position = "left"


# Bindings
config.bind("xt", "config-cycle tabs.show always never")
config.bind("xb", "config-cycle statusbar.show always never")
config.bind(
    "xx",
    "config-cycle statusbar.show always never;; config-cycle tabs.show always never",
)

config.bind("zm", "hint links spawn mpv {hint-url}")
config.bind(
    "zy", "hint links spawn alacritty -e yt-dlp {hint-url} -P ~/Videos/youtube/"
)


# AdBlock
c.content.blocking.enabled = True
c.content.blocking.method = "both"

# Dark mode
c.colors.webpage.darkmode.enabled = True

# URL
c.url.start_pages = ["https://google.com"]
c.url.searchengines = {
    "DEFAULT": "https://google.com/search?q={}",
    # "g": "https://google.com/search?q={}",
    # "gh": "https://github.com/search?q={}",
    # "yt": "https://youtube.com/results?search_query={}",
}

# User agent configuration
config.set(
    "content.headers.user_agent",
    "Mozilla/5.0 ({os_info}; rv:135.0) Gecko/20100101 Firefox/135.0",
    "https://accounts.google.com/*",
)

# Nord theme
config.source("nord.py")
