c = c
config = config
# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)

# Position of the tab bar.
# Type: Position
# Valid values:
#   - top
#   - bottom
#   - left
#   - right
c.tabs.position = "left"

config.bind("xt", "config-cycle tabs.show always never")

c.content.blocking.enabled = False

c.url.start_pages = ["https://google.com"]

c.url.searchengines = {
    "DEFAULT": "https://google.com/search?q={}",
    # "g": "https://google.com/search?q={}",
    # "gh": "https://github.com/search?q={}",
    # "yt": "https://youtube.com/results?search_query={}",
}


config.source("nord.py")
