alias nv='nvim'
alias jpl='jupyter lab'
alias envs='virtualenv venv'
alias enva='source venv/bin/activate'
alias envd='deactivate'
alias tm='tmux'
alias gitig='bash ~/bin/.local/scripts/git-ignore-template.sh'
