# alias ..='cd ..'
# alias egrep='egrep --color=auto'
alias enva='source .venv/bin/activate'
alias envc='virtualenv venv'
alias envd='deactivate'
# alias fgrep='fgrep --color=auto'
alias gitig='bash ~/scripts/git-ignore-template.sh'
alias grep='grep --color=auto'
alias jpl='jupyter lab'
# alias l='ls -CF --color=auto'
# alias la='ls -A --color=auto'
alias la='ls -a'
# alias ll='ls -laF --color=auto'
# alias ls='ls --color=auto'
alias nv='nvim'
alias tm='tmux'
alias tms='~/scripts/tmux-sessionizer'
alias tma='tmux a'
