# alias ..='cd ..'
# alias egrep='egrep --color=auto'
alias enva='source .venv/bin/activate'
alias envc='virtualenv venv'
alias envd='deactivate'
# alias fgrep='fgrep --color=auto'
alias gitig='bash ~/scripts/git-ignore-template.sh'
alias grep='grep --color=auto'
alias jpl='jupyter lab'
alias jplh='jpl --no-browser --port 8888'
alias jplb='ssh -NfL 8888:localhost:8888 simsam8@homelab && xgd-open http://localhost:8888' # bridge to homelab and open jupyterlab
# alias l='ls -CF --color=auto'
# alias la='ls -A --color=auto'
alias ll='ls -a'
# alias ll='ls -laF --color=auto'
# alias ls='ls --color=auto'
alias nv='nvim'
alias tm='tmux'
alias tms='~/scripts/tmux-sessionizer'
alias tma='tmux a'
